################################################################################
# Reproducibility check
################################################################################
# This script compares the audit results generated by running 05_audit_workflow.R 
# with the corresponding results obtained by the authors and reported in 
# folder ./simstudy/sim_results_A/audit/audit_by_authors.
################################################################################

# Session -> Set Working Directory -> To Source File Location
#setwd('/home/spreaficom/jmdf/simstudy')
setwd(file.path(getwd(),'simstudy'))

################################################################################
# Functions
################################################################################

# JMDF: compare audit and full-workflow results for a given setting,
# initialization/threshold combination, and estimation method.
audit.checks.jmdf <- function(setting, folder, method, 
                              tol = 1e-8, save.check = TRUE) {
  
  # The reproducibility check uses a user-defined numerical tolerance because
  # both Gaussian and Uniform initialization rely on an iterative EM algorithm.
  # The initialization also includes a stochastic assignment of observations to
  # the initial frailty support points. Small numerical differences can therefore
  # lead to slightly different convergence paths. For the Uniform initialization,
  # such differences may additionally affect the discrete support-reduction step
  # and, in some cases, the selected number of frailty groups. The default
  # tolerance is deliberately strict; larger tolerances can be specified to
  # assess agreement in the numerical estimates. 
  # The number of frailty groups (K) is checked separately and exactly, 
  # and any difference in K is reported explicitly.
  
  # Check that method is valid
  if (!method %in% c("gauss", "unif")) {
    stop("method must be either 'gauss' or 'unif'")
  }
  
  audit.checks <- do.call(
    rbind,
    # Loop over the nine simulation scenarios
    lapply(1:9, function(scenario) {
      
      # Load audit results
      audit.path = paste0("sim_results_",setting,"/audit/s",scenario,"_JMDF_",
                          method, folder,".Rdata")
      if (!file.exists(audit.path)) {
        stop("Audit results not found. Please run '05_audit_workflow.R' first.")
      }
      load(audit.path)
      coef.results.audit <- coef.results
      frail.results.audit <- frail.results
      
      
      # Load complete results
      authors.path = paste0("sim_results_",setting,"/audit/audit_by_authors/s",
                            scenario,"_JMDF_",method, folder,".Rdata")
      load(authors.path)
      coef.results.authors <- coef.results
      frail.results.authors <- frail.results
      
      # Compare the audit results with the corresponding first `audit.reps`
      # replications from the full simulation results
      audit.reps = nrow(coef.results.audit)
      # Model estimates and standard errors to be compared
      coef.vars = c("beta1", "beta2","gamma1", "gamma2",
                    "se_beta1", "se_beta2","se_gamma1", "se_gamma2")
      
      data.frame(
        scenario = scenario,
        replication = 1:audit.reps,
        
        # Compare coefficient estimates and SEs
        # excluding K, AIC, n.iter from the comparison
        coef.results = sapply(
          1:audit.reps,
          function(i)
            isTRUE(all.equal(
              coef.results.audit[i, coef.vars, drop = FALSE],
              coef.results.authors[i, coef.vars, drop = FALSE],
              tolerance = tol
            ))
        ),
        
        # Compare the number of frailty groups
        K = sapply(
          1:audit.reps,
          function(i) {
            coef.results.audit$K[i] ==
              coef.results.authors$K[i]
          }
        ),
        
        # Report the difference in the number of frailty groups
        K_difference = sapply(
          1:audit.reps,
          function(i) {
            coef.results.audit$K[i] -
              coef.results.authors$K[i]
          }
        ),
        
        # Compare frailty estimates only when K is the same
        frail.results = sapply(
          1:audit.reps,
          function(i) {
            
            K.audit <- coef.results.audit$K[i]
            K.authors <- coef.results.authors$K[i]
            
            if (K.audit != K.authors) {
              return("Not comparable")
            }
            
            # Fix label switching
            audit_i <- frail.results.audit[frail.results.audit$rep_b == i, , drop = FALSE]
            complete_i <- frail.results.authors[frail.results.authors$rep_b == i, , drop = FALSE]
            
            # Order groups by Pu
            audit_i <- audit_i[order(audit_i$Pu), , drop = FALSE]
            complete_i <- complete_i[order(complete_i$Pu), , drop = FALSE]
            
            # Remove group labels and rownames because they are arbitrary
            audit_i$group <- NULL
            complete_i$group <- NULL
            
            rownames(audit_i) <- NULL
            rownames(complete_i) <- NULL
            
            isTRUE(all.equal(audit_i, complete_i, tolerance = tol))
          }
        )
      )
    })
  )
  
  if(save.check){
    # Save check results
    res.path = paste0("sim_results_",setting,"/audit/reproducibility_check_",method,
                      "_",setting,"_", folder, ".csv")
    write.csv2(audit.checks, file = res.path, row.names = FALSE)
    cat(paste0('results saved in file: ',res.path))
    cat('\n')
  }
  
  return(audit.checks)
}

# Ng et al.: compare audit and full-workflow simulation results for a given setting
audit.checks.ng <- function(setting, tol = 10e-8, save.check = TRUE) {
  
  audit.checks <- do.call(
    rbind,
    lapply(1:9, function(scenario) {
      
      # Load audit results
      audit.path = paste0("sim_results_ng_",setting,"/audit/s",scenario,"_JMNg.Rdata")
      if (!file.exists(audit.path)) {
        stop("Audit results not found. Please run '05_audit_workflow.R' first.")
      }
      load(audit.path)
      sim.results.audit <- sim.results
      
      # Load complete results
      authors.path = paste0("sim_results_ng_", setting, "/audit/audit_by_authors/s",scenario,"_JMNg.Rdata")
      load(authors.path)
      sim.results.authors <- sim.results
      
      # Compare the audit results with the corresponding first `audit.reps`
      # replications from the full simulation results
      audit.reps = nrow(sim.results.audit)
      data.frame(
        scenario = scenario,
        replication = 1:audit.reps,
        
        sim.results = sapply(
          1:audit.reps,
          function(i)
            isTRUE(all.equal(
              sim.results.audit[i, , drop = FALSE],
              sim.results.authors[i, , drop = FALSE],
              tolerance = tol
            ))
        )
      )
    })
  )
  
  if(save.check){
    # Save check results
    res.path = paste0("sim_results_ng_",setting,"/audit/reproducibility_check_ng_",setting,".csv")
    write.csv2(audit.checks, file = res.path, row.names = FALSE)
    cat(paste0('results saved in file: ',res.path))
    cat('\n')
  }
  
  return(audit.checks)
}


################################################################################
# Final checks
#
# The audit workflow is performed for one representative simulation
# configuration for each estimation approach. For JMDF, Setting A with
# initialization (ii) and L = 1.5 is considered; the same setting is used
# for the Ng et al. model.
################################################################################

# We can evaluate reproducibility using different numerical tolerances.
# Strict tolerances assess near-exact numerical agreement, whereas larger
# tolerances assess whether the results agree within a small numerical
# difference.
#
# The number of frailty groups (K) is checked separately and exactly, since
# a difference in K represents a difference in the selected support rather
# than a simple numerical discrepancy. The K_difference column reports the
# difference between the number of groups obtained in the audit and in the
# corresponding full-workflow result: a value of 0 indicates identical K,
# whereas a negative or positive value indicates fewer or more groups,
# respectively, in the audit result.


# JMDF Gaussian initialization (ii) with L = 1.5
#----------------------------------------------------------------------
# Strict tolerance
rep_checks_gauss = audit.checks.jmdf(setting = "A", folder = "II_L15",
                                     method = "gauss", tol=1e-8, save.check=T)
print(rep_checks_gauss)


# JMDF Uniform initialization (ii) with L = 1.5
#----------------------------------------------------------------------
# Large tolerance
rep_checks_unif = audit.checks.jmdf(setting = "A", folder = "II_L15",
                                    method = "unif", tol=1e-2, save.check=F)
print(rep_checks_unif)

# Strict tolerance
rep_checks_unif = audit.checks.jmdf(setting = "A", folder = "II_L15",
                                    method = "unif", tol=1e-8, save.check=T)
print(rep_checks_unif)



# Ng et al. Model
#----------------------------------------------------------------------
rep_checks_ng = audit.checks.ng(setting = "A", tol=1e-8, save.check=T)
print(rep_checks_ng)
