################################################################################
# Reproducibility check
################################################################################
# This script compares the reduced audit results generated by
# 05_audit_workflow.R with the corresponding results from the full simulation
# workflow. The check covers the first five replications of each of the
# nine simulation scenarios.
################################################################################

# Session -> Set Working Directory -> To Source File Location
#setwd('/home/spreaficom/jmdf/simstudy')
setwd(file.path(getwd(),'simstudy'))

################################################################################
# Functions
################################################################################

# JMDF: compare audit and full-workflow results for a given setting,
# initialization/threshold combination, and estimation method.
audit.checks.jmdf <- function(setting, folder, method) {
  
  # Check that method is valid
  if (!method %in% c("gauss", "unif")) {
    stop("method must be either 'gauss' or 'unif'")
  }
  
  audit.checks <- do.call(
    rbind,
    # Loop over the nine simulation scenarios
    lapply(1:9, function(scenario) {
      
      # Load audit results
      audit.path = paste0("sim_results_",setting,"/audit/s",scenario,"_JMDF_gauss",
                          folder,".Rdata")
      load(audit.path)
      coef.results.audit <- coef.results
      frail.results.audit <- frail.results
      
      
      # Load complete results
      complete.path = paste0("sim_results_", setting, "/",folder, "/s",scenario,
                             "_JMDF_gauss", folder,".Rdata")
      load(complete.path)
      coef.results.complete <- coef.results
      frail.results.complete <- frail.results
      
      # Compare the audit results with the corresponding first `audit.reps`
      # replications from the full simulation results
      audit.reps = nrow(coef.results.audit)
      data.frame(
        scenario = scenario,
        replication = 1:audit.reps,
        
        coef.results = sapply(
          1:audit.reps,
          function(i)
            isTRUE(all.equal(
              coef.results.audit[i, , drop = FALSE],
              coef.results.complete[i, , drop = FALSE]
            ))
        ),
        
        frail.results = sapply(
          1:audit.reps,
          function(i)
            isTRUE(all.equal(
              frail.results.audit[i, , drop = FALSE],
              frail.results.complete[i, , drop = FALSE]
            ))
        )
      )
    })
  )
  
  # Save check results
  res.path = paste0("sim_results_",setting,"/audit/reproducibility_check_",method,
                    "_",setting,"_", folder, ".csv")
  write.csv2(audit.checks, file = res.path, row.names = FALSE)
  cat(paste0('results saved in file: ',res.path))
  cat('\n')
  
  return(audit.checks)
}

# Ng et al.: compare audit and full-workflow simulation results for a given setting
audit.checks.ng <- function(setting) {
  
  audit.checks <- do.call(
    rbind,
    lapply(1:9, function(scenario) {
      
      # Load audit results
      audit.path = paste0("sim_results_ng_",setting,"/audit/s",scenario,"_JMNg.Rdata")
      load(audit.path)
      sim.results.audit <- sim.results
      
      # Load complete results
      complete.path = paste0("sim_results_ng_", setting, "/s",scenario,"_JMNg.Rdata")
      load(complete.path)
      sim.results.complete <- sim.results
      
      # Compare the audit results with the corresponding first `audit.reps`
      # replications from the full simulation results
      audit.reps = nrow(sim.results.audit)
      data.frame(
        scenario = scenario,
        replication = 1:audit.reps,
        
        sim.results = sapply(
          1:audit.reps,
          function(i)
            isTRUE(all.equal(
              sim.results.audit[i, , drop = FALSE],
              sim.results.complete[i, , drop = FALSE]
            ))
        )
      )
    })
  )
  
  # Save check results
  res.path = paste0("sim_results_ng_",setting,"/audit/reproducibility_check_ng_",setting,".csv")
  write.csv2(audit.checks, file = res.path, row.names = FALSE)
  cat(paste0('results saved in file: ',res.path))
  cat('\n')
  
  return(audit.checks)
}


################################################################################
# Final checks
#
# The audit workflow is performed for one representative simulation
# configuration for each estimation approach. For JMDF, Setting A with
# initialization (ii) and L = 1.5 is considered; the same setting is used
# for the Ng et al. model.
################################################################################

# JMDF Gaussian initialization (ii) with L = 1.5
#----------------------------------------------------------------------
rep_checks_gauss = audit.checks.jmdf(setting = "A", folder = "II_L15",
                                     method = "gauss")
print(rep_checks_gauss)

# JMDF Uniform initialization (ii) with L = 1.5
#----------------------------------------------------------------------
rep_checks_unif = audit.checks.jmdf(setting = "A", folder = "II_L15",
                                    method = "unif")
print(rep_checks_unif)

# Ng et al. Model
#----------------------------------------------------------------------
rep_checks_ng = audit.checks.ng(setting = "A")
print(rep_checks_ng)
